services:
  - type: web
    name: audio-transcriber
    env: python
    region: frankfurt
    buildCommand: |
      wget https://alphacephei.com/vosk/models/vosk-model-ru-0.42.zip -O model.zip
      unzip model.zip
      rm model.zip
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
