services:
  - type: web
    name: audio-transcriber
    env: python
    region: frankfurt
    buildCommand: |
      mkdir -p vosk-model-small-ru-0.22
      wget https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip -O model.zip
      unzip model.zip -d vosk-model-small-ru-0.22
      rm model.zip
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MAX_AUDIO_DURATION
        value: "180"
