services:
  - type: web
    name: audio-transcriber
    env: python
    region: frankfurt
    buildCommand: |
      wget https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip -O model.zip
      unzip model.zip
      
      # Автодетект структуры
      if [ -f "vosk-model-small-ru-0.22/am/final.mdl" ]; then
          echo "Обнаружена новая структура архива"
      elif [ -f "vosk-model-small-ru-0.22/vosk-model-small-ru-0.22/am/final.mdl" ]; then
          echo "Обнаружена старая структура - исправляем"
          mv vosk-model-small-ru-0.22/vosk-model-small-ru-0.22/* vosk-model-small-ru-0.22/
          rm -rf vosk-model-small-ru-0.22/vosk-model-small-ru-0.22
      else
          echo "ОШИБКА: Неверная структура архива!"
          exit 1
      fi
      
      rm model.zip
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MAX_AUDIO_DURATION
        value: "300"
